name: Build session

on:
  push:
    branches: [ "CADE", "CADE_Typing" ]

  workflow_dispatch:

  permissions:
    contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: makarius/isabelle:Isabelle2022
      options: --user root

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Checkout AFP
        uses: actions/checkout@v3
        with:
          repository: isabelle-prover/mirror-afp-2022
          path: afp

      - name: Set Isabelle Home 
        run: |
          echo "$(/home/isabelle/Isabelle/bin/isabelle getenv ISABELLE_HOME)" >> $GITHUB_ENV

      - name: Set Isabelle Home User
        run: |
          echo "$($ISABELLE_HOME/bin/isabelle getenv ISABELLE_HOME_USER)" >> $GITHUB_ENV

      - name: Cache Heap Images
        uses: actions/cache@v3
        with:
          path: $ISABELLE_HOME_USER/heaps/
          key: heap-images-${{ github.ref_name }}
          restore-keys: heap-images-

      - name: Build Session
        run: |
          session="Set_Proc"
          if [ "$GITHUB_REF_NAME" = "CADE_Typing" ]; then
            session="Set_Proc_Typing"
          fi;
          $ISABELLE_HOME/bin/isabelle build -v -d src/ -d afp/thys -R $session
          $ISABELLE_HOME/bin/isabelle build -P browser_info -v -c -d src/ -d afp/thys $session

      - name: Upload browser_info to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: browser_info
          target-folder: ${{ github.ref_name }}
          single-commit: true
