name: Build session

on:
  push:
    branches: [ "CADE", "CADE_Typing" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: makarius/isabelle:Isabelle2022
      options: --user root

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Checkout AFP
        uses: actions/checkout@v3
        with:
          repository: isabelle-prover/mirror-afp-2022
          path: afp

      - name: Cache Heap Images
        uses: actions/cache@v3
        with:
          path: ~/.isabelle/heaps/
          key: heap-images-${{ github.ref_name }}
          restore-keys: heap-images-

      - name: Build Session
        run: |
          session="Set_Proc"
          if [ "$GITHUB_REF_NAME" = "CADE_Typing" ]; then
            session="Set_Proc_Typing"
          fi;
          /home/isabelle/Isabelle/bin/isabelle build -d src/ -d afp/thys -R $session
          /home/isabelle/Isabelle/bin/isabelle build -c -d src/ -d afp/thys $session

      - name: Upload browser_info
        uses: actions/upload-artifact@v3
        with:
          name: browser_info-${{ github.ref_name }}
          path: ~/.isabelle/browser_info/
